[package]
name = "i_am_mt"
version = "0.1.0"
authors = ["DCjanus <DCjanus@dcjanus.com>"]
edition = "2018"

[dependencies]
hex = "0.3"
byteorder = {version = "1", features = ["i128"]}
itertools = "0.7"

failure = "0.1"
rand = "0.6"

rust-crypto = "0.2"
